#! /bin/sh

# Usage: fill-appdir [pkg list]
#   The packages will be installed system-wide, then copied into ./AppDir.

debian () {
  sudo apt-get -qq --yes --force-yes update
  sudo apt-get -qq --yes --force-yes install "$@"
  dpkg-query -L "$@"
}

archlinux () {
  sudo pacman -Syu "$@"
  pacman -Qql "$@"
}

list () {
  command -v dpkg-query && debian "$@"
  command -v pacman     && archlinux "$@"
}

copy () {
  while read l; do
    test -d $l && mkdir -p AppDir/$l
    test -f $l && cp -a $l AppDir/$l
  done
}

list "$@" | sort -u | copy
